
//ADD TO CART
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET'


//REMOVE FROM CART
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL'
export const REMOVE_FROM_CART_RESET ='REMOVE_FROM_CART_RESET'


//REMOVE FROM CART
export const SHIPPING_ADDRESS_SUCCESS = 'SHIPPING_ADDRESS_SUCCESS'
export const SHIPPING_ADDRESS_FAIL = 'SHIPPING_ADDRESS_FAIL'
export const SHIPPING_ADDRESS_RESET ='SHIPPING_ADDRESS_RESET'

//PAYMENT METHOD
export const PAYMENT_METHOD_SUCCESS = 'PAYMENT_METHOD_SUCCESS'
export const PAYMENT_METHOD_FAIL = 'PAYMENT_METHOD_FAIL'
export const PAYMENT_METHOD_RESET ='PAYMENT_METHOD_RESET'