//CREATE ORDER
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

//GET ORDER
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'


//ORDER PAY
export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

//GET ORDER LIST
export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST'
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL'
export const GET_ORDER_LIST_RESET = 'GET_ORDER_LIST_RESET'

//GET ORDER LIST
export const UPDATE_DELIVERED_REQUEST = 'UPDATE_DELIVERED_REQUEST'
export const UPDATE_DELIVERED_SUCCESS = 'UPDATE_DELIVERED_SUCCESS'
export const UPDATE_DELIVERED_FAIL = 'UPDATE_DELIVERED_FAIL'
export const UPDATE_DELIVERED_RESET = 'UPDATE_DELIVERED_RESET'


//REMOVE ORDER 
export const REMOVE_ORDER_REQUEST = 'REMOVE_ORDER_REQUEST'
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS'
export const REMOVE_ORDER_FAIL = 'REMOVE_ORDER_FAIL'
export const REMOVE_ORDER_RESET = 'REMOVE_ORDER_RESET'