export const POST_PORT_CONTACT_REQUEST = 'POST_PORT_CONTACT_REQUEST'
export const POST_PORT_CONTACT_SUCCESS = 'POST_PORT_CONTACT_SUCCESS'
export const POST_PORT_CONTACT_FAIL = 'POST_PORT_CONTACT_FAIL'