//CREATE
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

//GET ALL PRODUCTS
export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'
export const GET_ALL_PRODUCTS_RESET = 'GET_ALL_PRODUCTS_RESET'

//GET PRODUCT BY ID
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

//UPDATE PRODUCT BY ID
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCTS_FAIL'
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCTS_RESET'

//REMOVE PRODUCT BY ID
export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_FAIL = 'REMOVE_PRODUCT_FAIL'
export const REMOVE_PRODUCT_RESET = 'REMOVE_PRODUCT_RESET'

//CREATE REVIEW 
export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

//GET TOP RATED PRODUCTS
export const TOP_RATED_PRODUCTS_REQUEST = 'TOP_RATED_PRODUCTS_REQUEST'
export const TOP_RATED_PRODUCTS_SUCCESS = 'TOP_RATED_PRODUCTS_SUCCESS'
export const TOP_RATED_PRODUCTS_FAIL = 'TOP_RATED_PRODUCTS_FAIL'

