//SEARCH  UNSPLASH API
export const IMAGE_SEARCH_REQUEST ='IMAGE_SEARCH_REQUEST'
export const IMAGE_SEARCH_SUCCESS ='IMAGE_SEARCH_SUCCESS'
export const IMAGE_SEARCH_FAIL ='IMAGE_SEARCH_FAIL'


//SEARCH YOUTUBE API
export const YOUTUBE_SEARCH_REQUEST ='YOUTUBE_SEARCH_REQUEST'
export const YOUTUBE_SEARCH_SUCCESS ='YOUTUBE_SEARCH_SUCCESS'
export const YOUTUBE_SEARCH_FAIL ='YOUTUBE_SEARCH_FAIL'


//YOUTUBE SEARCH REQUEST
export const YOUTUBE_CHOICE_SUCCESS ='YOUTUBE_CHOICE_SUCCESS'
export const YOUTUBE_CHOICE_FAIL ='YOUTUBE_CHOICE_FAIL'


//SEARCH WIKI API
export const WIKI_SEARCH_REQUEST ='WIKI_SEARCH_REQUEST'
export const WIKI_SEARCH_SUCCESS ='WIKI_SEARCH_SUCCESS'
export const WIKI_SEARCH_FAIL ='WIKI_SEARCH_FAIL'


//GET WEATHER 16 DAY FORCAST API 
export const GET_WEATHER_REQUEST ='GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS ='GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAIL ='GET_WEATHER_FAIL'

//GET WEATHER 24 HOUR FORECAST

export const GET_WEATHER_HOUR_REQUEST ='GET_WEATHER_HOUR_REQUEST'
export const GET_WEATHER_HOUR_SUCCESS ='GET_WEATHER_HOUR_SUCCESS'
export const GET_WEATHER_HOUR_FAIL ='GET_WEATHER_HOUR_FAIL'




//GET MARVEL PUBLIC COMICS API
export const GET_MARVEL_REQUEST = 'GET_MARVEL_REQUEST'
export const GET_MARVEL_SUCCESS = 'GET_MARVEL_SUCCESS'
export const GET_MARVEL_FAIL = 'GET_MARVEL_FAIL'


//GET MARVEL CHARACTER API
export const GET_MARVEL_CHAR_REQUEST = 'GET_MARVEL_CHAR_REQUEST'
export const GET_MARVEL_CHAR_SUCCESS = 'GET_MARVEL_CHAR_SUCCESS'
export const GET_MARVEL_CHAR_FAIL = 'GET_MARVEL_CHAR_FAIL'


//GET MARVEL CHARACTER API
export const GET_COMIC_BY_ID_REQUEST = 'GET_COMIC_BY_ID_REQUEST'
export const GET_COMIC_BY_ID_SUCCESS = 'GET_COMIC_BY_ID_SUCCESS'
export const GET_COMIC_BY_ID_FAIL = 'GET_COMIC_BY_ID_FAIL'