
//SEARCH CHOICE 
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
//SEARCH CHOICE, ADD TO HISTORY 
export const SEARCH_HISTORY_ERASE = 'SEARCH_HISTORY_ERASE'
export const SEARCH_HISTORY_ERASE_FAIL = 'SEARCH_HISTORY_ERASE_FAIL'

//ADD TO YOUTUBE PLAYLIST
export const ADD_TO_YOUTUBE_PLAYLIST_SUCCESS = 'ADD_TO_YOUTUBE_PLAYLIST_SUCCESS'
export const ADD_TO_YOUTUBE_PLAYLIST_ERROR = 'ADD_TO_YOUTUBE_PLAYLIST_ERROR'

//REMOVE FROM YOUTUBE PLAYLIST
export const REMOVE_FROM_YOUTUBE_PLAYLIST_SUCCESS = 'REMOVE_FROM_YOUTUBE_PLAYLIST_SUCCESS'
export const REMOVE_FROM_YOUTUBE_PLAYLIST_ERROR = 'REMOVE_FROM_YOUTUBE_PLAYLIST_ERROR'