export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const GET_ALLUSERS_REQUEST = 'GET_ALLUSERS_REQUEST'
export const GET_ALLUSERS_SUCCESS = 'GET_ALLUSERS_SUCCESS'
export const GET_ALLUSERS_FAIL = 'GET_ALLUSERS_FAIL'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'

export const UPDATE_USER_BY_ID_REQUEST = 'UPDATE_USER_BY_ID_REQUEST'
export const UPDATE_USER_BY_ID_SUCCESS = 'UPDATE_USER_BY_ID_SUCCESS'
export const UPDATE_USER_BY_ID_FAIL = 'UPDATE_USER_BY_ID_FAIL'
export const UPDATE_USER_BY_ID_RESET = 'UPDATE_USER_BY_ID_RESET'

export const DELETE_USER_REQUEST ='DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS ='DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL ='DELETE_USER_FAIL'
export const DELETE_USER_RESET ='DELETE_USER_RESET'


export const LOGOUT = 'LOGOUT'